version: "2"

services:
  kit-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kit-api
    volumes:
    - ./:/code
    env_file:
      - .env.docker
    restart: unless-stopped
    command: >
        bash -c "flask run"
    ports:
      - "8007:8007"
    networks:
      - kit-network


networks:
  kit-network:
    driver: bridge
