version: "2"

services:
  mongo:
    image: mongo
    restart: always
    networks:
      - kit-network
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - kit-network
    ports:
      - 8081:8081

  kit-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kit-api
    volumes:
    - ./:/code
    env_file:
      - .env.docker
    restart: unless-stopped
    command: >
        bash -c "flask run"
    ports:
      - "8007:8007"
    networks:
      - kit-network
    depends_on:
      - mongo

networks:
  kit-network:
    driver: bridge
